### ISSUE TITLE
A menu to toggle some filter

### ISSUE THREAD

**Issue by mefengl** [antfu/userscript-clean-twitter#3]
### Clear and concise description of the problem

like this
![image](https://user-images.githubusercontent.com/71683364/234464475-8c79141c-9d7e-4541-a6a5-75a3ad02c2b2.png)

### Suggested solution

code likes like this:

```javascript
const default_menu_all = {
  foo: true,
  bar: false,
};
const menu_all = GM_getValue("menu_all", default_menu_all);

// use GM_registerMenuCommand and GM_unregisterMenuCommand to create menu
...

if (menu_all.foo) {
  // do foo
}

if (menu_all.bar) {
 // do bar
}
```

### Additional context

If this script needs it, I will submit a pull request

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for the tips, it's good to know!

However, I am not sure if we need this, anything you think is worth toggling?

**Comment by mefengl** [comment]
`Pinned Lists`? But this may just be my personal need.

current:
![image](https://user-images.githubusercontent.com/71683364/234467035-19b10ff4-1da8-4c80-b647-6276c0ba35ab.png)

before filter:
![image](https://user-images.githubusercontent.com/71683364/234467117-767c49cd-2121-4473-909e-121e7923aaee.png)

If it's just about filter rule issues, there is indeed no need to add this feature.

**Comment by antfu** [comment]
Interesting, I don't know you can pin lists. In that sense I am open to PR to toggle it
