### ISSUE TITLE
Doesn't Work on Safari?

### ISSUE THREAD

**Issue by Jagerx** [antfu/userscript-clean-twitter#7]
### Describe the bug

It doesn't seem to work on:
Safari 16.5 (18615.2.9.11.4)
<img width="1229" alt="2023-05-30_14-43-18" src="https://github.com/antfu/userscript-clean-twitter/assets/42521386/59e49ed7-2a04-40d8-95db-2c95cd464ab3">

### Reproduction

n/a

### System Info

```Shell
Tampermonkey 4.17.6162
Clean Twitter: 0.3.1 up to date
```

### Used Package Manager

npm

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't use Safari and have no incentive to test it. It's a short script, it's better to test on your own and send a PR to fix it if you want to. Thanks.
